<?php

namespace Ethanzway\IAP\ValueObjects;

/**
 * Receipt Class
 * This class represents the decoded version of the encoded receipt data sent
 * with the request to the App Store.
 */
final class Receipt
{
    const RECEIPT_TYPE_PRODUCTION = 'Production';
    const RECEIPT_TYPE_PRODUCTION_VPP = 'ProductionVPP';
    const RECEIPT_TYPE_SANDBOX = 'ProductionSandbox';
    const RECEIPT_TYPE_PRODUCTION_VPP_SANDBOX = 'ProductionVPPSandbox';

    /**
     * @var string|null
     * @see \Ethanzway\IAP\ValueObjects\Receipt::$appItemId
     */
    private $adamId;

    /**
     * Originally, this is 64-bit long integer, so, let's treat is a string
     * to be in the safe side.
     * Generated by App Store Connect and used by the App Store to
     * uniquely identify the app purchased.
     * Apps are assigned this identifier only in production.
     * @var string|null
     */
    private $appItemId;

    /**
     * The app’s version number. In the sandbox, the value is always "1.0".
     * @var string|null
     */
    private $applicationVersion;

    /**
     * The bundle identifier for the app to which the receipt belongs.
     * @var string|null
     */
    private $bundleId;

    /**
     * A unique identifier for the app download transaction.
     * @var int|null
     */
    private $downloadId;

    /**
     * The time the receipt expires for apps purchased through the Volume Purchase Program
     * @var int|null
     */
    private $expirationDate;

    /**
     * An array that contains the in-app purchase receipt fields for all in-app purchase transactions.
     * @var array|null
     */
    private $inApp;

    /**
     * The version of the app that the user originally purchased.
     * @var string|null
     */
    private $originalApplicationVersion;

    /**
     * The time of the original app purchase
     * @var int|null
     */
    private $originalPurchaseDate;

    /**
     * The time the user ordered the app available for pre-order.
     * @var int|null
     */
    private $preOrderDate;

    /**
     * The time the App Store generated the receipt
     * @var int|null
     */
    private $receiptCreationDate;

    /**
     * The type of receipt generated.
     * The value corresponds to the environment in which the app or VPP purchase was made
     * @var string|null
     */
    private $receiptType;

    /**
     * The time the request to the verifyReceipt endpoint was processed and the response was generated
     * @var int|null
     */
    private $requestDate;

    /**
     * An arbitrary number that identifies a revision of your app.
     * In the sandbox, this key's value is “0”
     * @var int|null
     */
    private $versionExternalIdentifier;

    /**
     * @var bool
     */
    private $inAppParsed;

    /**
     * Receipt Constructor
     */
    public function __construct()
    {
        $this->inAppParsed = false;
    }

    /**
     * @param array $attributes
     * @return static
     */
    public static function fromArray(array $attributes)
    {
        $obj = new self();
        $obj->adamId = $attributes['adam_id'] ?? null;
        $obj->appItemId = $attributes['app_item_id'] ?? null;
        $obj->applicationVersion = $attributes['application_version'] ?? null;
        $obj->bundleId = $attributes['bundle_id'] ?? null;
        $obj->downloadId = $attributes['download_id'] ?? null;
        $obj->inApp = $attributes['in_app'] ?? null;
        $obj->originalPurchaseDate = $attributes['original_purchase_date_ms'] ?? null;
        $obj->receiptCreationDate = $attributes['receipt_creation_date_ms'] ?? null;
        $obj->receiptType = $attributes['receipt_type'] ?? null;
        $obj->requestDate = $attributes['request_date_ms'] ?? null;
        $obj->versionExternalIdentifier = $attributes['version_external_identifier'] ?? null;
        $obj->originalApplicationVersion = $attributes['original_application_version'] ?? null;
        $obj->expirationDate = $attributes['expiration_date_ms'] ?? null;
        $obj->preOrderDate = $attributes['preorder_date_ms'] ?? null;

        return $obj;
    }

    /**
     * @return string|null
     */
    public function getAdamId()
    {
        return $this->adamId;
    }

    /**
     * @return string|null
     */
    public function getAppItemId()
    {
        return $this->appItemId;
    }

    /**
     * @return string|null
     */
    public function getApplicationVersion()
    {
        return $this->applicationVersion;
    }

    /**
     * @return string|null
     */
    public function getBundleId()
    {
        return $this->bundleId;
    }

    /**
     * @return int|null
     */
    public function getDownloadId()
    {
        return $this->downloadId;
    }

    /**
     * @return Time|null
     */
    public function getExpirationDate()
    {
        return
            $this->expirationDate ?
                new Time($this->expirationDate) :
                null;
    }

    /**
     * @return array|LatestReceiptInfo[]|null
     */
    public function getInApp()
    {
        if (is_null($this->inApp) || $this->inAppParsed) {
            return $this->inApp;
        }

        $data = [];
        foreach ($this->inApp as $receiptData) {
            $data[] = LatestReceiptInfo::fromArray($receiptData);
        }

        $this->inAppParsed = true;
        $this->inApp = $data;

        return $this->inApp;
    }

    /**
     * @return string|null
     */
    public function getOriginalApplicationVersion()
    {
        return $this->originalApplicationVersion;
    }

    /**
     * @return Time|null
     */
    public function getOriginalPurchaseDate()
    {
        return
            $this->originalPurchaseDate ?
                new Time($this->originalPurchaseDate) :
                null;
    }

    /**
     * @return Time|null
     */
    public function getPreOrderDate()
    {
        return
            $this->preOrderDate ?
                new Time($this->preOrderDate) :
                null;
    }

    /**
     * @return Time|null
     */
    public function getReceiptCreationDate()
    {
        return
            $this->receiptCreationDate ?
                new Time($this->receiptCreationDate) :
                null;
    }

    /**
     * @return string|null
     */
    public function getReceiptType()
    {
        return $this->receiptType;
    }

    /**
     * @return Time|null
     */
    public function getRequestDate()
    {
        return
            $this->requestDate ?
                new Time($this->requestDate) :
                null;
    }

    /**
     * @return int|null
     */
    public function getVersionExternalIdentifier()
    {
        return $this->versionExternalIdentifier;
    }
}
